alter table SOLOCEJASAPP_VENTA add constraint FK_SOLOCEJASAPP_VENTA_ON_SERVICIO_3 foreign key (SERVICIO_3_ID) references SOLOCEJASAPP_SERVICIO(ID);
create index IDX_SOLOCEJASAPP_VENTA_ON_SERVICIO_3 on SOLOCEJASAPP_VENTA (SERVICIO_3_ID);
