alter table SOLOCEJASAPP_VENTA add constraint FK_SOLOCEJASAPP_VENTA_ON_SERVICIO_1 foreign key (SERVICIO_1_ID) references SOLOCEJASAPP_SERVICIO(ID);
create index IDX_SOLOCEJASAPP_VENTA_ON_SERVICIO_1 on SOLOCEJASAPP_VENTA (SERVICIO_1_ID);
