alter table SOLOCEJASAPP_REPORTE add constraint FK_SOLOCEJASAPP_REPORTE_ON_VENDEDORA foreign key (VENDEDORA_ID) references SEC_USER(ID);
alter table SOLOCEJASAPP_REPORTE add constraint FK_SOLOCEJASAPP_REPORTE_ON_LOCAL foreign key (LOCAL_ID) references SOLOCEJASAPP_LOCAL(ID);
create index IDX_SOLOCEJASAPP_REPORTE_ON_VENDEDORA on SOLOCEJASAPP_REPORTE (VENDEDORA_ID);
create index IDX_SOLOCEJASAPP_REPORTE_ON_LOCAL on SOLOCEJASAPP_REPORTE (LOCAL_ID);
