alter table SOLOCEJASAPP_VENTA add constraint FK_SOLOCEJASAPP_VENTA_ON_SERVICIO foreign key (SERVICIO_ID) references SOLOCEJASAPP_SERVICIO(ID);
create index IDX_SOLOCEJASAPP_VENTA_ON_SERVICIO on SOLOCEJASAPP_VENTA (SERVICIO_ID);
