alter table SOLOCEJASAPP_VENTA add constraint FK_SOLOCEJASAPP_VENTA_ON_SERVICIO_2 foreign key (SERVICIO_2_ID) references SOLOCEJASAPP_SERVICIO(ID);
create index IDX_SOLOCEJASAPP_VENTA_ON_SERVICIO_2 on SOLOCEJASAPP_VENTA (SERVICIO_2_ID);
